services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp/maildir
  redis:
    image: redis:6.2.6
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/volume:/data
    restart: always
